# fly.toml app configuration file generated for loan-backend on 2025-03-01T21:32:16+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'loan-backend'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
